language: node_js
node_js:
- node
notifications:
  email: false
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: dvtA7AqrxwDP5qHWuHs/X2pMPx4Pso/jHTWiPkL+Jksgo57teuLf9cdxjjUbCkomJ7BTbgtT2H6uqhmR1DKZgfUHVOuntv3mUlr34jOgCag74iwMPw9wFErDu6FuPIlJgeIhuFsSIKChyxguKdbHBu/fMjIkVcnXVc/K77tebOwaVatSC7WlpOaOTU4JlaYC7BVjVGwqgiGlMgGrKBOYmsRLL2FDOhx0cTa+p3d5ODI8eqTBeD92/mjdOIEAs5p20IRlqk7xj1BnpX6gPyoxkDBDnePg+tn2FXFzIqtAv19FRjoJ2GzvueeDl/bEsr0hgpxd6QNnPu4X6l7xKOezznviDDW3kDJx5sd4jQgNk02OFUfKgGxDCw0HlWXEHLEXhwq+pWRmNqoDH/h0fDzVN28QMnJaqOneaavAOscsECXxFmHyU8DDa9Cr7qPQfPDLwnYkDTMFDJxQvN4tZjtULs5GvRR0lQ2MfZj9uXRKHor9jhWr3GfFOTOh5eKodhZ4+FCLuxRRj3mWpZCA5Axd7yU8TBU+uypGYBY0IXC+mZO+Iez8x7iEC7pTujXbUMzh5iQuhwLUls0CaramjVLlSxOLUZ3tWn16LXzRW2c6t2zSq1SKoIQCUjjXkrgaiMGHb/AWSMfiVkIb21e81jvxWwv8HxEWUublVGA45IMlxLA=
  app: dream-up-pup
