language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  app: dream-up-pup
  api_key:
    secure: GcA6ovWGbzny0KxfFRAZzm4O51cycoHoL+yeRha3hvj8CivjjrCBnWwYzkd5YGXqjkSo2fFf3U9lMrVqVlksbx6w0ZEcPCDzEV7aiBSHqOj+WYAzILSO94XgXTDlZobNfFyTGCY38PB5CnMaRVeOUj689eEceTBswGdXci2B4Rrjtfl7wvj9jvFTurW7WiYqFpXqqI/j/CN+cgz5VQCWFJLzpXSNtiAiSeVxqUBV+bWYFG7yQO+T5tbRcsYGwAuuJ714CjCSKR2haV6Jutue20YrRUU7OfE2vf15RlrcSWvqwPun1ydFdIEVGfBQ9gA6sOV+2K6VEs27tXuFWEflfV72o7SHm0JFH6iLLJjISKyqvoSp57K6BjWw5yGcox+jmZMb/YkP5ems8rnGy3GKijr2T9vDlQrW0GOB+s4cEn98r6DF5FfJAKhsaOQPo557fZMu4a7fREFgud+pYUNxrAV+NwxHP2T9lED05HD3kpRDDb0l2VlRwYHe7OyhvoL4X30b03h5q1HMBJoK88rTLdN8kN6iLOlaC2tm0LLRL/t7eBmyrwuYzbBBnxDwPEcywzrfv6Yvu2j7Atv2nPbjMx+UH4kMXJtn2oMenhEHfsusEgEwKjrjw7ebGLkWxvEc3oeS7DvQKIavUIwxBvAkqTbQSLmqkKv7IV4IF5M2OK4=
